name: geocompy
channels:
  - conda-forge
dependencies:
  - bokeh
  - branca
  - cartopy>=0.22
  - contextily
  - cython
  - fiona>=1.9
  - folium
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jupyter
  - jupyterlab
  - mapclassify
  - matplotlib
  - nbformat
  - numpy
  - osmnx
  - pandas
  - prettymaps
  - proj
  - quarto
  - rasterio
  - rasterstats
  - richdem
  - shapely
  - topojson
